spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost         # The hostname or IP address of the Redis server. 'localhost' refers to the local machine (127.0.0.1).
    port: 6379              # The port on which the Redis server is listening. 6379 is the default port for Redis.
    password:        # The password used to authenticate with the Redis server. This should match the password configured in Redis.
    timeout: 2000           # The connection timeout in milliseconds (2000ms = 2 seconds). This is the maximum time the client will wait for a response from the Redis server.
    lettuce:                # Lettuce is the Redis client used by Spring Boot. This section configures the connection pool settings for Lettuce.
      pool:
        max-active: 8       # Maximum number of active connections in the pool. These are the connections that can be used simultaneously.
        max-idle: 8         # Maximum number of idle connections in the pool. These are the connections that are open but not currently being used.
        min-idle: 0         # Minimum number of idle connections in the pool. The pool will try to maintain at least this many idle connections.
        max-wait: -1ms      # Maximum time (in milliseconds) the client will wait for a connection to become available when the pool is exhausted. -1ms means to wait indefinitely.

server:
  port: 8080

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
  type-aliases-package: com.mall.mall_backend.domain.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志级别输出sql
    map-underscore-to-camel-case: true   #驼峰下划线转换

#    如果查询结果是 Map<String, Object>: mapUnderscoreToCamelCase 不适用，键名不会自动转换为驼峰命名。如果你想要在这种情况下将键名转换为驼峰命名，你需要手动处理，比如遍历 Map 并手动转换键名。
#
#    如果查询结果是 DTO 类: mapUnderscoreToCamelCase 仍然适用，MyBatis 会自动将下划线命名的字段映射到驼峰命名的属性。





